language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
# Using manage.py validate since there are no unit tests yet
script:  python manage.py validate